// Industries/Departments
export const industries = [
  'Technology & IT',
  'Finance & Banking',
  'Healthcare & Medical',
  'Education & Training',
  'Marketing & Advertising',
  'Sales & Business Development',
  'Human Resources',
  'Engineering & Manufacturing',
  'Design & Creative',
  'Customer Service & Support',
  'Operations & Logistics',
  'Legal & Compliance',
  'Real Estate & Construction',
  'Retail & E-commerce',
  'Hospitality & Tourism',
  'Media & Entertainment',
  'Agriculture & Food',
  'Energy & Utilities',
  'Consulting & Strategy',
  'Research & Development',
];

// Job roles categorized by industry
export const rolesByIndustry = {
  'Technology & IT': [
    'Software Engineer',
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'DevOps Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'Cloud Architect',
    'Cybersecurity Analyst',
    'QA Engineer',
    'Product Manager',
    'UI/UX Designer',
    'Mobile Developer',
    'Database Administrator',
    'System Administrator',
    'AI Engineer',
    'Blockchain Developer',
  ],
  'Finance & Banking': [
    'Financial Analyst',
    'Investment Banker',
    'Accountant',
    'Risk Manager',
    'Auditor',
    'Compliance Officer',
    'Portfolio Manager',
    'Tax Consultant',
    'Credit Analyst',
    'Treasury Manager',
  ],
  'Healthcare & Medical': [
    'Doctor',
    'Nurse',
    'Medical Assistant',
    'Pharmacist',
    'Lab Technician',
    'Physical Therapist',
    'Healthcare Administrator',
    'Medical Researcher',
    'Radiologist',
    'Surgeon',
  ],
  'Education & Training': [
    'Teacher',
    'Professor',
    'Curriculum Designer',
    'Corporate Trainer',
    'Educational Counselor',
    'Instructional Designer',
    'Academic Coordinator',
    'E-Learning Specialist',
  ],
  'Marketing & Advertising': [
    'Digital Marketing Manager',
    'SEO Specialist',
    'Content Writer',
    'Social Media Manager',
    'Brand Manager',
    'Marketing Analyst',
    'Growth Hacker',
    'Email Marketing Specialist',
    'Copywriter',
    'Performance Marketer',
  ],
  'Sales & Business Development': [
    'Sales Executive',
    'Business Development Manager',
    'Account Manager',
    'Sales Director',
    'Inside Sales Representative',
    'Regional Sales Manager',
    'Key Account Manager',
    'Sales Operations Manager',
  ],
  'Human Resources': [
    'HR Manager',
    'Recruiter',
    'Talent Acquisition Specialist',
    'HR Business Partner',
    'Compensation & Benefits Manager',
    'Training & Development Manager',
    'HR Generalist',
    'Employee Relations Manager',
  ],
  'Engineering & Manufacturing': [
    'Mechanical Engineer',
    'Electrical Engineer',
    'Civil Engineer',
    'Production Manager',
    'Quality Engineer',
    'Process Engineer',
    'Industrial Engineer',
    'Manufacturing Engineer',
  ],
  'Design & Creative': [
    'Graphic Designer',
    'UI/UX Designer',
    'Product Designer',
    'Creative Director',
    'Motion Graphics Designer',
    'Illustrator',
    'Brand Designer',
    'Art Director',
  ],
  'Customer Service & Support': [
    'Customer Support Executive',
    'Customer Success Manager',
    'Technical Support Engineer',
    'Call Center Agent',
    'Customer Experience Manager',
    'Support Team Lead',
  ],
  'Operations & Logistics': [
    'Operations Manager',
    'Supply Chain Manager',
    'Logistics Coordinator',
    'Warehouse Manager',
    'Procurement Specialist',
  ],
  'Consulting & Strategy': [
    'Business Analyst',
    'Management Consultant',
    'Strategy Consultant',
    'Operations Consultant',
  ],
};

// Popular roles for discovery grid - 16 roles
export const popularRoles = [
  {
    id: 1,
    name: 'Software Engineer',
    icon: 'code',
    count: 1250,
    industry: 'Technology & IT',
  },
  {
    id: 2,
    name: 'Product Manager',
    icon: 'dashboard',
    count: 890,
    industry: 'Technology & IT',
  },
  {
    id: 3,
    name: 'Data Scientist',
    icon: 'analytics',
    count: 756,
    industry: 'Technology & IT',
  },
  {
    id: 4,
    name: 'UI/UX Designer',
    icon: 'design_services',
    count: 634,
    industry: 'Design & Creative',
  },
  {
    id: 5,
    name: 'Digital Marketing',
    icon: 'campaign',
    count: 892,
    industry: 'Marketing & Advertising',
  },
  {
    id: 6,
    name: 'Sales Executive',
    icon: 'trending_up',
    count: 1120,
    industry: 'Sales & Business Development',
  },
  {
    id: 7,
    name: 'HR Manager',
    icon: 'people',
    count: 445,
    industry: 'Human Resources',
  },
  {
    id: 8,
    name: 'Financial Analyst',
    icon: 'account_balance',
    count: 567,
    industry: 'Finance & Banking',
  },
  {
    id: 9,
    name: 'Content Writer',
    icon: 'edit',
    count: 423,
    industry: 'Marketing & Advertising',
  },
  {
    id: 10,
    name: 'DevOps Engineer',
    icon: 'settings',
    count: 678,
    industry: 'Technology & IT',
  },
  {
    id: 11,
    name: 'Business Analyst',
    icon: 'business',
    count: 534,
    industry: 'Consulting & Strategy',
  },
  {
    id: 12,
    name: 'Accountant',
    icon: 'receipt',
    count: 789,
    industry: 'Finance & Banking',
  },
  {
    id: 13,
    name: 'Database Admin',
    icon: 'storage',
    count: 445,
    industry: 'Technology & IT',
  },
  {
    id: 14,
    name: 'Customer Support',
    icon: 'support_agent',
    count: 823,
    industry: 'Customer Service & Support',
  },
  {
    id: 15,
    name: 'Operations Manager',
    icon: 'local_shipping',
    count: 512,
    industry: 'Operations & Logistics',
  },
  {
    id: 16,
    name: 'AI/ML Engineer',
    icon: 'psychology',
    count: 689,
    industry: 'Technology & IT',
  },
];